### PR TITLE
docs: fix typo in MAINTAINERS.md

### PR DESCRIPTION
**Pull request by evankanderson**
## Description

I was reading the MAINTAINERS.md, and I noticed a repeated word.

## Type of change

Governance "change" (cleanup).

## How Has This Been Tested?

Not at all.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by ashearin — APPROVED** [review]

**Review by jhoward-lm — APPROVED** [review]

**Comment by jhoward-lm** [comment]
@evankanderson I updated the title of the PR to a conventional commit so that changelog generation works correctly. Thanks for fixing the typo!

**Comment by ashearin** [comment]
@evankanderson Looks like your initial commit was unsigned, which is required to get it merged. Are you able to squash and recommit with a signature?

**Comment by evankanderson** [comment]
Done, and I added a note to `CONTRIBUTING.md` to indicate that commits need to be signed, since I didn't see it in the directions.

**Comment by evankanderson** [comment]
Oh, and I also updated the `CONTRIBUTING.md` instructions to highlight that the PR title needs to match conventional commits, not just the commit messages.

**Pull request merged**
